### PR TITLE
Add Travis config 

### PR DESCRIPTION
**Pull request by CodeFromCirc**
`npm test` is basically a JS style check using `standard`, you can change it to use eslint

### CODE REVIEW

**Comment by Devoxin** [comment]
i love this PR is ironic because travis failed

**Comment by JustMaffie** [comment]
HAHAHAHAHAHAHAHAHAHAHA

**Comment by CodeFromCirc** [comment]
@Devoxin got a fix coming:tm:

**Comment by perryprog** [comment]
dun dun dun

**Comment by Devoxin** [comment]
stop spamming my hecking inbox

**Comment by perryprog** [comment]
ping

**Comment by Devoxin** [comment]
BOI

**Comment by natanbc** [comment]
and build failed again :lul:

**Comment by perryprog** [comment]
lul emoji

**Comment by Devoxin** [comment]
why

**Comment by lepon01** [comment]
Btw this is better than Discord

**Comment by Devoxin** [comment]
yea, actually works

**Comment by lepon01** [comment]
owo

**Comment by lepon01** [comment]
circuit forked

**Comment by perryprog** [comment]
# also better markdown support

**Comment by atiwiex** [comment]
Why are you doing this on github 👏

**Comment by Devoxin** [comment]
lets fucc

**Comment by JustMaffie** [comment]
@lepon01 Circuit forked ~~you~~

**Comment by perryprog** [comment]
no

**Comment by lepon01** [comment]
no i do not consent

**Comment by Devoxin** [comment]
same

**Comment by lepon01** [comment]
gmail is fucked

**Comment by perryprog** [comment]
I unsubscribed so I'm cool

**Comment by Devoxin** [comment]
someone update the damn PR to force travis to rebuild

**Comment by lepon01** [comment]
Please do that

**Comment by Devoxin** [comment]
no u

**Comment by perryprog** [comment]
darn, nvm

hec

also, I believe it has to be merged with master again because there were some changes pushed to master

**Comment by perryprog** [comment]
¯\_(ツ)_/¯

**Comment by Devoxin** [comment]
hey you dropped an arm

**Comment by JustMaffie** [comment]
lol, u merged a broken pr into master well done

**Comment by lepon01** [comment]
¯\\_(ツ)_/¯

**Comment by perryprog** [comment]
o rly

**Comment by lepon01** [comment]
great i lost my arms

**Comment by Devoxin** [comment]
@JustMaffie not broken ~~unlike u~~

**Comment by perryprog** [comment]
@JustMaffie ur face is broken

**Comment by lepon01** [comment]
`¯\\\_(ツ)\_/¯`
¯\\\_(ツ)\_/¯

**Comment by Devoxin** [comment]
¯\\\_(ツ)\_/¯

**Comment by perryprog** [comment]
I fixed it a while ago tho

**Comment by natanbc** [comment]
¯\\\_(ツ)\_/¯

**Comment by perryprog** [comment]
¯\\\_(ツ)\_/¯

**Comment by Devoxin** [comment]
terminal in emoji code when

**Comment by perryprog** [comment]
soon™

**Comment by natanbc** [comment]
lolcode is better

**Comment by perryprog** [comment]
`MjM4NDk0NzU2NTIxMzc3Nzky.CunGFQ.wUILz7z6HoJzVeq6pyHPmVgQgV4`

oops finger slipped

**Comment by lepon01** [comment]
lolicode?

**Comment by Devoxin** [comment]
BANNED

**Comment by perryprog** [comment]
why isn't Natan a member

**Comment by CodeFromCirc** [comment]
lolcode isn't used
emojicode is

**Comment by Devoxin** [comment]
he's not cool that's why

**Comment by natanbc** [comment]
idk, plsfix

**Comment by lepon01** [comment]
**Did you mean:** _JavaScript_?

**Comment by natanbc** [comment]
@Devoxin heck off

**Comment by MrLar** [comment]
Only professionals here tbh

**Comment by CodeFromCirc** [comment]
why do i feel like i wasted my time

**Comment by Devoxin** [comment]
@natanbc <3

**Comment by natanbc** [comment]
@CodeFromCirc because you did

**Comment by perryprog** [comment]
@CodeFromCirc no clue

**Comment by CodeFromCirc** [comment]
@natanbc welp, now i feel like leaving terminal
..but i have no botlist to go to

**Comment by perryprog** [comment]
anyway, I have some popcorn if anyone is interested 🍿

**Comment by CodeFromCirc** [comment]
nah

**Comment by perryprog** [comment]
I'd just like to interject for a moment. What you're referring to as Terminal, is in fact, ls.terminal.ink, or as I've recently taken to calling it, the "Terminal.ink Bot List". Terminal is not a bot list unto itself, but is rather another free component of a fully functioning community made useful by Terminal.ink.

Many users use a modified version of the Terminal Bot List software every day, without realising it. Through a peculiar turn of events, the version of ls.terminal.ink, which is widely used today is often called Terminal, and many users are not aware that it is basically the Terminal Bot List, developed by Terminal.ink

The Terminal Bot List is really a part of Terminal.ink, and these people are using it, but it is just part of the community they partake in. Terminal.ink is an essential part of the community, which has other useful services such as a paint program, API for bots, and more. Saying Terminal while meaning the bot list is confusing to others.

**Comment by Devoxin** [comment]
fucking copypasta get banned

**Comment by natanbc** [comment]
@CodeFromCirc that's why you shouldn't mute evade :lul:

**Comment by lepon01** [comment]
alex

**Comment by perryprog** [comment]
@Devoxin is this normal for a terminal issue

**Comment by lepon01** [comment]
No

**Comment by CodeFromCirc** [comment]
@lepon01's profile pic explains it all

**Comment by natanbc** [comment]
no and that needs to change

**Comment by perryprog** [comment]
aaaaaaaa poor Alex

quick lock the issue

**Comment by atiwiex** [comment]
🛑

**Comment by lepon01** [comment]
Where's the lock button

**Comment by natanbc** [comment]
idk

**Comment by perryprog** [comment]
checking, 1 sec

**Comment by lepon01** [comment]
found it

Found it

**Comment by CodeFromCirc** [comment]
near the bottom iirc

**Comment by natanbc** [comment]
i think it's next to comment

**Comment by Devoxin** [comment]
hi i feel special

**Comment by lepon01** [comment]
ffs everyone is a member

**Comment by TheUnitedStatesOfAmerica** [comment]
Serious mode, you should include building docker too because that automatically tests deployment so that we don't have to worry about master being broken @CodeFromCirc , dont have to do it yourself if you dont want to though, can add it later myself

**Pull request merged**
