### PR TITLE
Wew docker support

### PR DESCRIPTION
**Pull request by JustMaffie**

### CODE REVIEW

**Comment by Devoxin** [comment]
Ew docker

**Comment by TriggerRimfire** [comment]
@JustMaffie Can you update it to use alpine instead?

**Comment by JustMaffie** [comment]
@TriggerRimfire why

**Comment by atiwiex** [comment]
Alpine is light weight and perfect for docker.

**Comment by ohlookitsAugust** [comment]
yes Alpine is lightweight 👌

**Comment by lepon01** [comment]
If it's better and you can do it, I think you should use it.

**Comment by JustMaffie** [comment]
I'll make a new PR

**Pull request merged**
