### PR TITLE
Updated french translation with missing labels

### PR DESCRIPTION
**Pull request by thibautbessone**
Did you know ? In France, it is legal to marry a dead person

### CODE REVIEW

**Comment by lepon01** [comment]
How interesting!

**Comment by thibautbessone** [comment]
If the body agreed to marry you, that goes without saying

**Comment by lepon01** [comment]
heejin being cute

**Comment by thibautbessone** [comment]
uwu 
image

**Comment by lepon01** [comment]
jinsoul hit u with love

**Comment by thibautbessone** [comment]
*falls dead*

_tfw when you use github as a forum to post cute girls though_

**Pull request merged**
