### PR TITLE
fixed some grammar and made it US friendly

### PR DESCRIPTION
**Pull request by Habchy**
why do british people use "S" in place of "Z"?

### CODE REVIEW

**Comment by lepon01** [comment]
Because it's correct

**Comment by Devoxin** [comment]
*sips tea*

**Comment by lepeli** [comment]
u Fish and chips

**Comment by atiwiex** [comment]
u baguette

**Comment by lepon01** [comment]
Line 65 has invalid JSON.

**Comment by TriggerRimfire** [comment]
how the hell do you manage to mess that up

**Comment by natanbc** [comment]
not testing it

**Comment by lepeli** [comment]
@atiwiex u big mac

**Pull request merged**
